export const categories = [
  "Fantasy",
  "Horror",
  "Maze",
  "Civilization",
  "Fan Expansion",
  "Negotiation",
  "Medieval",
  "Ancient",
  "Card Game",
  "Dice",
  "Print & Play",
  "City Building",
  "Economic",
  "Abstract Strategy",
  "Renaissance",
  "Animals",
  "Bluffing",
  "Deduction",
  "Party Game",
];
